quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://tfb-database/hello_world
"%dev":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://localhost/hello_world
