quarkus:
  datasource:
    db-kind: mysql
    reactive:
      url: mysql://tfb-database:3306/hello_world
"%dev":
  quarkus:
    datasource:
      reactive:
        url: mysql://localhost:3306/hello_world
