quarkus:
  datasource:
    db-kind: mysql
    reactive:
      url: jdbc:mysql://tfb-database/hello_world
"%dev":
  quarkus:
    datasource:
      reactive:
        url: jdbc:mysql://localhost/hello_world
